site_name: "Programming Practices for Research in Economics: Foundations"
pages:
-  Course Home Page: index.md
- Announcements: announcements.md
- Schedule: schedule.md
- Course Material: material.md
- About the Instructors: about.md
- Acknowledgements: acknowledgements.md
- License: license.md
theme:
    name: material
    # logo: 'assets/pp4rs.png'
markdown_extensions:
  - admonition
  - pymdownx.superfences
